### ISSUE TITLE
Installation procedure

### ISSUE THREAD

**Issue by mailsonsantos** [matthewtckr/pdi-google-drive-plugin#1]
I saw the wiki and found it quite interesting, how do I install the plugin?

**Comment by matthewtckr** [comment]
Hi @mailsonsantos, I'll have to revisit this and look into getting it into the marketplace, but for now, you can download from the [releases page](https://github.com/matthewtckr/pdi-google-drive-plugin/releases), and unzip the file into the `data-integration/plugins` directory.

**Comment by mailsonsantos** [comment]
@matthewtckr Thank you very much. I will carry out the procedure
